# -*- coding: utf-8 -*-
"""overall_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThfWtRiKKpCOR-C9XcAif8INVnq5Z2v5
"""

# ======================================================
# ⚽ Premier League Overall Points Predictor
# ======================================================

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# ======================================================
# 1️⃣ Page Configuration
# ======================================================
st.set_page_config(
    page_title="⚽ Overall Points Predictor",
    page_icon="🏆",
    layout="wide"
)

st.title("🏆 Premier League Overall Points Predictor")
st.markdown("Predict a team's **total points** based on their season stats!")

# ======================================================
# 2️⃣ Load Trained Model
# ======================================================
@st.cache_resource
def load_model():
    return joblib.load("linear_regression_model.pkl")

model = load_model()
st.success("✅ Model loaded successfully!")

# ======================================================
# 3️⃣ Input Features (as per your dataset)
# ======================================================
st.subheader("📋 Enter Team Details")

col1, col2, col3 = st.columns(3)

with col1:
    season_end_year = st.number_input("Season End Year (e.g., 2024)", min_value=1990, max_value=2100, step=1)
    team = st.text_input("Team Name (e.g., Arsenal)")

with col2:
    played = st.number_input("Matches Played", min_value=0, step=1)
    won = st.number_input("Matches Won", min_value=0, step=1)

with col3:
    lost = st.number_input("Matches Lost", min_value=0, step=1)
    drawn = st.number_input("Matches Drawn", min_value=0, step=1)

# ======================================================
# 4️⃣ Prepare Input DataFrame
# ======================================================
input_data = pd.DataFrame({
    'season_end_year': [season_end_year],
    'team': [team],
    'played': [played],
    'won': [won],
    'lost': [lost],
    'drawn': [drawn]
})

# ======================================================
# 5️⃣ Predict Points
# ======================================================
if st.button("🔮 Predict Total Points"):
    if team.strip() == "":
        st.warning("Please enter the team name before predicting.")
    else:
        predicted_points = model.predict(input_data)[0]
        st.success(f"🏅 **Predicted Total Points:** {predicted_points:.2f}")

# ======================================================
# 6️⃣ Footer
# ======================================================
st.markdown("---")
st.caption("Built with ❤️ using Streamlit and Linear Regression Model")